version: '3'
services:
  personal-api:
    image: "vvraju056/22it056-personal-api"
    ports:
      - "5000:5000"

  friends-api:
    image: "nithimahesh/22itl09-personal-api"
    ports:
      - "90:5000"
